image: quay.io/buildah/stable:v1.34.0

stages:
  - build_and_deploy

job:
  stage: build_and_deploy
  script:
    - dnf install -y qemu-user-static
    - bash build.sh "$ALPINE_VERSION" "$CI_REGISTRY_USER" "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY" "$CI_REGISTRY_IMAGE"

variables:
  ALPINE_VERSION: "3.19"
